#!/bin/sh

# Inspired from https://github.com/pystardust/ani-cli
# written in pure posix script. shellcheck is regularly run and it is tested to run with dash. 
# except the coreutils, mpv are dependencies

# setting the url cause i'm impatient and can't wait for 2 fucking seconds to get the working url. if urls changes run the recache url function. i'm too lazy
base_url="https://gogoanime.fi/"

# history file
logfile="$HOME/.cache/ani-hsts"

# exiting function
exiting() {
    notify-send "😔 Exiting.... 🔴" "$1" && exit
}

# beautifully stolen from https://github.com/pystardust/ani-cli
search_anime () {
	search=$(printf '%s' "$1" | tr ' ' '-' )

	curl -s "$base_url//search.html" \
		-G \
		-d "keyword=$search" |
	sed -n -E '
		s_^[[:space:]]*<a href="/category/([^"]*)" title="([^"]*)".*_\1_p
		'
}

# searching for the anime
get_name() {
    query="$(: | dmenu -p 'Search Anime:')"
    [ -z "$query" ] && exiting "Nothing entered"

    search_results="$(search_anime "$query")"
    [ -z "$search_results" ] && exiting "No anime found"

    anime_name="$(printf '%s' "$search_results" | dmenu -p "Select Anime:" -l 15)"
    [ -z "$anime_name" ] && exiting "No anime selected"

    choose_epi
}

# beautifully stolen from https://github.com/pystardust/ani-cli
search_eps () {
	anime_id=$1

	curl -s "$base_url/category/$anime_id" |
	sed -n -E '
		/^[[:space:]]*<a href="#" class="active" ep_start/{
		s/.* '\''([0-9]*)'\'' ep_end = '\''([0-9]*)'\''.*/\2/p
		q
		}
		'
}

# getting the episode number. don't be a dick and enter number which isn't possible. the script won't tell your computer that you entered something wrong
choose_epi() {
    no_of_epis="$(search_eps "$anime_name")"

    if [ "$no_of_epis"  = 1 ]; then
      epi=1
    else
      epi="$(: | dmenu -p "Choose episode [1-$no_of_epis]:")"
      [ -z "$epi" ] && exiting "Nothing entered"
    fi

    get_url_play 
}

# beautifully stolen from https://github.com/pystardust/ani-cli
get_dpage_link() {
	anime_id=$1
	ep_no=$2

	anime_page=$(curl -s "$base_url/$anime_id-$ep_no")

	if printf '%s' "$anime_page" | grep -q "404" ; then
		anime_page=$(curl -s "$base_url/$anime_id-episode-$ep_no")
	fi

	printf '%s' "$anime_page" | sed -n -E 's/.*class="active" rel="1" data-video="([^"]*)".*/\1/p' | sed 's/^/https:/g'
}

# beautifully stolen from https://github.com/pystardust/ani-cli
decrypt_link() {
	secret_key='3235373136353338353232393338333936313634363632323738383333323838'
	iv='31323835363732393835323338333933'
	ajax_url="https://gogoplay4.com/encrypt-ajax.php"
	crypto_data=$(curl -s "$1" | sed -nE 's/.*data-value="([^"]*)".*/\1/p')
	id=$(printf '%s' "$crypto_data" | base64 -d | openssl enc -d -aes256 -K "$secret_key" -iv "$iv" | cut -d '&' -f1)

	#encrypt and create the final ajax
	ajax=$(printf "%s\010\016\003\010\t\003\004\t" "$id" | openssl enc -aes256 -K "$secret_key" -iv "$iv" -a)

	#send request and get the data(most lamest way)
	data=$(curl -s -H "X-Requested-With:XMLHttpRequest" "$ajax_url" -d "id=$ajax" | sed -e 's/{"data":"//' -e 's/"}/\n/' -e 's/\\//g')
	
	#decrypt the data to get final links
	printf '%s' "$data" | base64 -d | openssl enc -d -aes256 -K "$secret_key" -iv "$iv" | sed -e 's/\].*/\]/' -e 's/\\//g' |
		grep -Eo 'https:\/\/[-a-zA-Z0-9@:%._\+~#=][a-zA-Z0-9][-a-zA-Z0-9@:%_\+.~#?&\/\/=]*'
}

# to run after the exiting mpv
after_choose() {
    no_of_epis="$(search_eps "$anime_name")"

    choice="$(printf "Next episode($((epi+1)))\nPrevious episode($((epi-1)))\nSelect episode[1-$no_of_epis]\nReplay current episode($epi)\nSearch for another anime\nSearch history" | dmenu -l 6 -i -p "Choose:")"
    [ -z "$choice" ] && exiting "Nothing entered"

    case $choice in
        "Next episode($((epi+1)))") epi=$((epi + 1)) && get_url_play ;;
        "Previous episode($((epi-1)))") epi=$((epi - 1)) && get_url_play ;;
        "Select episode[1-$no_of_epis]") choose_epi ;;
        "Replay current episode($epi)") get_url_play ;;
        "Search for another anime") get_name ;;
        "Search history") get_history ;;
    esac
}

# making so that you remember which episode you watched last
append_to_hist() {
    grep "$anime_name\s" "$logfile" && sed -e '/'"$anime_name"'\t.*/d' -i "$logfile" && printf "%s\t%d\n" "$anime_name" "$epi" >> "$logfile" ||
    printf "%s\t%d\n" "$anime_name" "$epi" >> "$logfile"
}

# to print the history
get_history() {
    search_results="$(tac "$logfile" | sed 's/\t[0-9]*//' )"
    [ -z "$search_results" ] && exiting "History is empty"

    anime_name="$(printf '%s' "$search_results" | dmenu -p "Choose:" -i -l 15)"
    [ -z "$anime_name" ] && exiting "Nothing chosen"

    no_of_epis="$(search_eps "$anime_name")"
    epi=$(sed -n -E "s/${anime_name}\t//p" "$logfile") 

    whether_to_continue=$(printf "Continue from left($epi)\nGo to next episode($((epi + 1)))\nSelect episode[1-$no_of_epis]\nSearch history\nSearch for another anime" | dmenu -i -l 5 -p "Choose:" )
    [ -z "$whether_to_continue" ] && exiting "Nothing chosen"

    case $whether_to_continue in
        "Continue from left($epi)") get_url_play ;;
        "Go to next episode($((epi + 1)))") epi=$((epi + 1)) && get_url_play ;;
        "Select episode[1-$no_of_epis]") choose_epi ;;
        "Search history") get_history ;;
        "Search for another anime") get_name ;;
    esac
}

# getting the url and opening it in mpv
get_url_play() {
    dpage_url="$(get_dpage_link "$anime_name" "$epi")"
    urls="$(decrypt_link "$dpage_url")"
    video_link=$(printf '%s' "$urls" | head -n 4 | tail -n 1)
    append_to_hist
    mpv --referrer="$dpage_url" --force-media-title="$anime_name ep-$epi" "$video_link" && after_choose || exiting "Some error happened"
}

# for recaching the url
recache_web() {
    base_url=$(curl -s -L -o /dev/null -w "%{url_effective}\n" https://gogoanime.cm) && sed 's|^base_url.*|base_url="'"$base_url"'"|' -i "$0" && main
}

# the main function
main() {
    what_to_do="$(printf "Search web\nSearch history\nRecache url"| dmenu -i -l 3 -p "What to do?")"
    [ -z "$what_to_do" ] && exiting "Nothing entered"

    case $what_to_do in 
        "Search web") get_name ;;
        "Search history") get_history ;;
        "Recache url") recache_web || exiting "Failed to refresh url" ;;
    esac
}

# run it now quick
main
