#!/bin/sh

# INIT
printf "$$" > ~/.cache/pidofbar
sec=0

# MODULES
update_time() {
	time="$(date "+[%a %d %b] [%I:%M %P]")" 
}

update_vol() {
	vol="$([ "$(pamixer --get-mute)" = "false" ] && printf '🔊' || printf '🔇')$(pamixer --get-volume)%"
}

update_nettraf() {
	net="$($HOME/.local/bin/statusbar/nettraf)"
}

# modules that don't update on their own need to be run at the start for getting their initial value
update_vol
# to update it from external commands
## kill -m "$(cat ~/.cache/pidofbar)"
# where m = 34 + n

display() {
	echo " [$net] [$vol] [$time] "
}

# SIGNALING
trap	"update_vol;display"		"RTMIN"

while true
do
	sleep 1 & wait && {
		[ $((sec % 5 )) -eq 0 ] && update_time
		[ $((sec % 5 )) -eq 0 ] && update_nettraf

		# how often the display updates ( 5 seconds )
		[ $((sec % 5 )) -eq 0 ] && display
		sec=$((sec + 1))
	}
done
