#!/bin/sh
# SPDX-License-Identifier: MIT

## Copyright (C) 2011 Przemyslaw Pawelczyk <przemoc@gmail.com>
##
## This script is licensed under the terms of the MIT license.
## https://opensource.org/licenses/MIT
#
# Usage: gitio URL [CODE]
#
# Turns a github.com URL
#  into a git.io URL
#
# Copies the git.io URL to your clipboard if xclip is available.

URL="$1"
CODE="$2"

if ! expr "${URL}" : "\(\(https\?://\)\?\(gist\.\)\?github.com/\)" >/dev/null; then
	echo "* github.com URLs only" >&2
	exit 1
fi

if ! expr "${URL}" : "http" >/dev/null; then
	URL="https://${URL}"
fi

OUT="$(\
	curl -si https://git.io -F "url=${URL}" ${CODE:+-F "code=${CODE}"} | \
	sed '/^Status: /{s///;/^201/d;q};/^Location: /!d;s///'
	)"

if expr "${OUT}" : "[0-9]\+" >/dev/null; then
	echo "${OUT}" >&2
	exit 1
fi

echo "${OUT}"
which xclip >/dev/null && echo "${OUT}" | xclip -selection clipboard
