#!/bin/bash

# Source pywal colors
source ~/.cache/wal/colors.sh

# Read the template and replace color placeholders
sed \
    -e "s/COLOR0/$color0/g" \
    -e "s/COLOR1/$color1/g" \
    -e "s/COLOR2/$color2/g" \
    -e "s/COLOR3/$color3/g" \
    -e "s/COLOR4/$color4/g" \
    -e "s/COLOR5/$color5/g" \
    -e "s/COLOR6/$color6/g" \
    -e "s/COLOR7/$color7/g" \
    -e "s/COLOR8/$color8/g" \
    -e "s/COLOR9/$color9/g" \
    -e "s/COLOR0/$color0/g" \
    ~/.config/niri/config.templates.kdl > ~/.config/niri/config.kdl


