#!/usr/bin/env sh

menu() {
	printf "lock\n"
	printf "suspend\n"
	printf "hibernate\n"
	printf "logout\n"
	printf "reboot\n"
	printf "poweroff\n"
}

choice=$(menu | tofi)

case "$choice" in
	lock) $HOME/.scripts/system/waylock.sh ;;
	suspend) systemctl suspend ;;
	hibernate) systemctl hibernate ;;
	logout) killall Hyprland ;;
	reboot) systemctl reboot ;;
	poweroff) systemctl poweroff ;;
esac
