#!/bin/bash

# Source pywal colors
source ~/.cache/wal/colors.sh

# Generate the waybar style.css file
sed \
    -e "s/COLOR0/${color0}/g" \
    -e "s/COLOR0/${color0}/g" \
    -e "s/COLOR1/${color1}/g" \
    -e "s/COLOR7/${color7}/g" \
    -e "s/COLOR8/${color8}/g" \
    -e "s/COLOR15/${color15}/g" \
    ~/.config/waybar/style.template.css > ~/.config/waybar/style.css

