#!/bin/sh
mkdir -p "$HOME/hdd/vids/recordings"
path="$HOME/hdd/vids/recordings"
[ -z "$1" ] && printf "Enter filename: " && read name || name=$(printf '%s' "$*")
printf "[a] record with audio\n[n] record without audio\n"
printf ": " && read ch
case $ch in
    a)
        wf-recorder --audio --file="$path/$name.mp4";;
    n)
        wf-recorder -f "$path/$name.mp4";;
    *)
        printf "%s\n" "error detected";;
esac
