#!/bin/sh

path="$HOME/vids/recordings"

config_dir="${XDG_CONFIG_HOME:-$HOME/.config}"
[ -e "$config_dir/demonrecord/config" ] && . "$config_dir/demonrecord/config"

mkdir -p "$path"

[ -z "$1" ] && printf "Enter filename: " && read name || name=$(printf '%s' "$*")

printf "[a] record with desktop audio\n[m] record with mic\n[n] record without audio\n[q] quit\n"

printf ": " && read ch

case $ch in
    a)
        wf-recorder --audio=alsa_output.pci-0000_00_1f.3.analog-stereo.monitor --force-yuv --file="$path/$name.mkv";;
    m)
        wf-recorder --audio=alsa_output.pci-0000_00_1f.3.analog-stereo --force-yuv --file="$path/$name.mkv";;
    n)
        wf-recorder --force-yuv -f "$path/$name.mkv";;
    q)
        exit 0;;
    *)
        printf "%s\n" "error detected";;
esac
