#!/usr/bin/env sh

path_to_ss="$HOME/pix/screenshots/screenshot_$(date +%s).png"
scrot -s -F "$path_to_ss"
xclip -sel c -t image/png "$path_to_ss"
notify-send "🖼️ Scrot 🖼️" "Screenshot copied to clipboard"

