#!/bin/sh
source_string=$(cat ~/.scripts/data/translator/languages.txt | rofi -dmenu -i -p 'Translate from:')
[ -z "$source_string" ] && exit

target_string=$(cat ~/.scripts/data/translator/languages.txt | rofi -dmenu -i -p 'Translate to:')
[ -z "$target_string" ] && exit

query=$(echo "" | rofi -dmenu -p "Translate text:") 
[ -z "$query" ] && exit
[ "$query" == "cc" ] && query=$(wl-paste || xclip -selection clipboard -o )

source_lang=$(jq ".$source_string" ~/.scripts/data/translator/languages.json)
target_lang=$(jq ".$target_string" ~/.scripts/data/translator/languages.json)

#translated=$(curl -X POST -F "source=$source_lang" -F "q=$query" -F "target=$target_lang" https://libretranslate.com/translate  | jq .translatedText | sed "s/\"//g")

#translated=$(curl -X POST -H "Content-Type: application/json" -d "{\"q\": \"$query\",\"source\": \"$source_string\",\"target\": \"$target_string\",\"format\": \"text\",\"api_key\": \"\"}" https://libretranslate.com/translate)

curl "https://api.mymemory.translated.net/get?q=$query&langpair=$source_string|$target_string"

#echo "$translated"
