#!/bin/sh

nsxiv_opts="-tfpo"
walldir="$HOME/pix/wall"

menu() {
	printf "set a wallpaper\n"
	printf "set a random wallpaper\n"
	printf "exit\n"
}

set_wal() {
	wal=$(nsxiv "$nsxiv_opts" "$walldir")
	feh --bg-fill "$wal"
	wal -i "$wal"
	pywalfox install
}

set_random() {
	wal=$(ls -d ~/pix/wall/* | shuf -n 1)
	feh --bg-fill "$wal"
	wal -i "$wal"
	pywalfox install
}

choice=$(menu | dmenu -i -p "What You Want To Do?" -l 3 | awk '{print $3}')

case $choice in
	wallpaper)
		set_wal
		;;
	random)
		set_random
		;;
	*)
		exit 0
		;;
esac
