#!/bin/sh

nsxiv_opts="-tfpo"
walldir="$HOME/hdd/pix/wall"

menu() {
	printf "%s\n" "set a wallpaper"
	printf "%s\n" "set a random wallpaper"
	printf "%s\n" "exit"
}

set_wal() {
	wal=$(nsxiv "$nsxiv_opts" "$walldir")
	swaybg -i "$wal" &
	#wal -i "$wal"
}

set_random() {
	wal=$(ls -d ~/pix/wall/* | shuf -n 1)
	swaybg -i "$wal" &
	#wal -i "$wal"
}

choice=$(menu | tofi | awk '{print $3}')

case $choice in
	wallpaper)
		set_wal
		;;
	random)
		set_random
		;;
	*)
		exit 0
		;;
esac
