#!/bin/sh

[ -z "$1" ] && printf "Enter url: " && read -r url || url=$1

fetch=$(curl -sL "$url&pbj=1" -H"x-youtube-client-name: 1" -H"x-youtube-client-version: 2.20230102.00.00" | sed -nE 's|.*251,"url":"([^"]*)".*|\1|p' | sed 's|\\u0026|\&|g')

mpv "$fetch"
