#!/bin/bash

file=$(find $HOME/.scripts/ -type f | dmenu -i -l 20)
cat "$file" | curl -F 'f:1=<-' ix.io | xclip -selection c
notify-send "😀 pastebin for $file created."

url=$(echo "$(xclip -sel c -o)")
time=$(date '+%d-%m-%y-%H_%M_%S')
title="[$time] 	$url 	$file"
echo "$title" >> "$HOME/hdd/dox/0x0/ix-logs.txt"
