#!/bin/sh
mkdir -p "$HOME/dox/0x0"

sel=$(printf "videos\nphotos" | rofi -dmenu)

file=""

if [ $sel == "videos" ]; then 
  file=$(find $HOME/vids -type f | rofi -dmenu)
else 
  file=$(find $HOME/pix -type f | rofi -dmenu)
fi

curl -s -F "file=@$file" https://upfast.cronyakatsuki.xyz | wl-copy
notify-send "Your file uploaded to 0x0.st server :)"

url=$(echo "$(wl-paste)")
time=$(date '+%d-%m-%y-%H_%M_%S')
title="[$time] 	$url 	${file}"
echo "$title" >> "$HOME/dox/0x0/0x0-logs.txt"

