#!/bin/bash

chosen=$(rofi -theme "~/.config/rofi/icons.rasi" -show file-browser-extended -file-browser-dir ~/Files/emojis -file-browser-cmd echo -file-browser-hide-parent -show-icons)
#[ -z "$chosen" ] && exit
#printf "https://gitlab.com/thecashewtrader/emojis/-/raw/main/$chosen" | xclip -sel c
cat "$chosen" | wl-copy
#xdotool key ctrl+v
#sleep 0.15
#xdotool key Return

