#!/bin/bash

echo "$(basename $0")

chosen=$(rofi -show file-browser-extended -file-browser-dir ~/Files/emojis -file-browser-cmd basename -file-browser-hide-parent -show-icons -config ~/.config/rofi/wallpaper.rasi)

[ -z "$chosen" ] && exit
printf "https://gitlab.com/thecashewtrader/emojis/-/raw/main/$chosen" | wl-copy
wtype -M ctrl v
sleep 0.15
wtype -P Return
