#!/usr/bin/env sh

menu() {
	printf "No\n"
	printf "Yes\n"
}

choice=$(menu | dmenu -p "Are You Sure?")


case $choice in
	"No")
		exit 1
		;;
	"Yes")
		shutdown -h now
		;;
	*)
		notify-send "nothing selected" && exit 1
		;;
esac
